function VolLoadresult = importVolLoadResultFile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  VOLLOADRESULTNORMAL = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  VOLLOADRESULTNORMAL = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  VolLoadresultnormal = importfile("C:\home\UMICH\Valsalva\Results\VolLoad_result_normal_.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Oct-2021 11:47:22

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 23);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["dVol", "vol", "time", "eGFR", "p_int", "HR", "CO", "CVP", "PCWP", "EF", "EDV", "BPm", "BPs", "BPd", "Qlymph", "V_Isf_Rel", "V_Isf_Exc", "ESP", "EDP", "Pwr_RV", "Pwr_LV", "dCar_d", "dAor_d"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
VolLoadresult = readtable(filename, opts);
VolLoadresult.Pwr_r = VolLoadresult.Pwr_LV./VolLoadresult.Pwr_RV;
VolLoadresult.Pwr_LVr = VolLoadresult.Pwr_LV/VolLoadresult.Pwr_LV(1); % ratio to baseline
VolLoadresult.Pwr_RVr = VolLoadresult.Pwr_RV/VolLoadresult.Pwr_RV(1); %ratio to baseline
VolLoadresult.Pwr_LVrn = VolLoadresult.Pwr_LV/1.25; % ratio to normal baseline
VolLoadresult.Pwr_RVrn = VolLoadresult.Pwr_RV/0.247; % ratio to normal baseline
VolLoadresult.SV = VolLoadresult.CO./VolLoadresult.HR*1000;

VolLoadresult.VP_r = VolLoadresult.CVP./VolLoadresult.PCWP;
VolLoadresult.BPpp = VolLoadresult.BPs - VolLoadresult.BPd;
VolLoadresult.LVSWI = VolLoadresult.SV/1.7.*(VolLoadresult.BPm - VolLoadresult.EDP)*13.6/1000; % Sanghvi 1972, 10.1161/01.CIR.46.4.780

i_baseline = find(min(VolLoadresult.dVol.^2) == VolLoadresult.dVol.^2);
VolLoadresult.SVrn = VolLoadresult.SV / VolLoadresult.SV(i_baseline);
VolLoadresult.dPCWP = VolLoadresult.PCWP - VolLoadresult.PCWP(i_baseline);

end